# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4a30841bd1417ca515adfe35a966d30c247dafd9335881bfe51dc81ebc7cf0b60beaf395e9f742db65b54c791dcb6a5fe15ba17dfa9cb360807f68d49c5fe97

test:
  secret_key_base: 8955d9f4bbd252a1bcd37ed27440d4fc281046428d4065b88de027ad790e91209f1666863650dd840e0ed0d12fee77ae0032ff47d436682ef251278e5fe4c3d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
